name: 'Upload to play store'
description: 'Uploads the supplied aabs to the Google Play Store'

inputs:
  aab-paths:
    description: 'App bundle paths to upload, JSON object'
    required: false
    default: 'production'
  package-name:
    description: 'App package name'
    required: false
    default: 'uk.gov.onelogin'

runs:
  using: "composite"
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Update fastlane and upload to play store
      run: |
        bundle update fastlane
        
        BUNDLES=($(echo $INPUT_AAB_PATHS | tr ";" "\n"))
        
        for BUNDLE in ${BUNDLES[@]}
        do
          echo "Bundle = $BUNDLE" 
          IFS=: VER=(${BUNDLE})
  
          FLAVOR=${VER[0]}
          AAB_PATH=${VER[1]}
          echo "Flavor = $FLAVOR"
          echo "AAB path = $AAB_PATH"
        
          case $FLAVOR in
            production*) PACKAGE_NAME=$INPUT_PACKAGE_NAME;;
            *) PACKAGE_NAME=${INPUT_PACKAGE_NAME}.${FLAVOR};;
          esac
        
          echo "Package name = $PACKAGE_NAME"
        
          export SUPPLY_UPLOAD_MAX_RETRIES=5
          bundle exec fastlane supply --package_name "${PACKAGE_NAME}" --json_key_data "${JSON_KEY_DATA}" --aab ${AAB_PATH} --track internal
        done
      shell: bash
      env:
        LC_ALL: en_GB.UTF-8
        LANG: en_GB.UTF-8
        INPUT_AAB_PATHS: ${{ inputs.aab-paths }}
        INPUT_PACKAGE_NAME: ${{ inputs.package-name }}
